title: Elysée Aristide Houndetoungan
email: ahoundetoungan@gmail.com
description: Assistant Professor of Economics
url: "https://ahoundetoungan.com/"  # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: aristide_eh
github_username:  ahoundetoungan
theme: jekyll-theme-minimal
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-feed
