title: Elysée Aristide Houndetoungan
email: ariel92and@gmail.com
description: Welcome to my personal website. I am a Ph.D candidate in Economics at Laval University. My research is mainly focused on the Econometrics of Social Networks.
url: "https://ahoundetoungan.com/"  # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ariel2299
github_username:  ahoundetoungan
theme: jekyll-theme-minimal
description: Ph.D Candidate in Economics at the Univertsité Laval
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
url: "https://ahoundetoungan.com/"
plugins:
  - jekyll-sitemap
  - jekyll-feed
