title: Elysée Aristide Houndetoungan
email: ariel92and@gmail.com
description: Ph.D candidate in Economics at Laval University
url: "https://ahoundetoungan.com/"  # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ariel2299
github_username:  ahoundetoungan
theme: jekyll-theme-minimal
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-feed
